version: '3.9'

services:
  db:
   image: postgres:14-alpine
   restart: always
   ports:
     - '5432:5432'
   environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=dilip_ecommerce
      - POSTGRES_PASSWORD=ecommerce

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PG_USER=dilip_ecommerce
      - PG_PASSWORD=ecommerce
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    volumes:
      - ./backend:/app/backend
    depends_on:
     - db

